import UseScrollEffect from "@HOOK/monitorScroll";
import "./globals.css";
import Link from "next/link";
import { ContactUS, Logo, PhoneIcon } from "@ELEMENT/svgIcons";
import styles from './layout.module.scss';
import Footer from "./Footer";
import { Suspense } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const iconItems = [
  { label: 'Call', icon: <PhoneIcon key={0} />, onClick: () => { } },
  { label: 'Mail', icon: <ContactUS key={1} />, onClick: () => { } },
];
const renderIconButton = ({ label, icon, onClick }) => (
  <button key={label} onClick={'onClick'} aria-label={label}>
    {icon}
  </button>
);
export default function RootLayout({ children, navbar }) {
  return (
    <html lang="en">
      <body >
        <header className={styles.nav} id="navbar">
          <Link className={styles.logo} href="/">
            <Logo />
            <h1>Medical <br />Innovative Wellness</h1>
          </Link>
          {navbar || 'N'}
          <nav className={styles.shortMenu}>{iconItems.map(renderIconButton)}</nav>
          <UseScrollEffect navbarId="navbar" activeClass={styles.scrolled} threshold={10} />
        </header>
        {children}
        <Suspense >
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
