import UseScrollEffect from "@HOOK/monitorScroll";
import "./globals.css";
import Link from "next/link";
import { ContactUS, Mail,Logo, PhoneIcon } from "@ELEMENT/svgIcons";
import styles from './layout.module.scss';
import Footer from "./Footer";
import { Suspense } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const iconItems = [
  { label: 'Call', icon: <PhoneIcon key={0} />, href: 'tel:(305)864-1373' },
  { label: 'Mail', icon: <Mail key={1} />, href: 'mailto:info@innovativemedicalwellness.com' },
  { label: 'Contact', icon: <ContactUS key={2} />, href: '/contact' },
];
const renderIconButton = ({ label, icon, href }) => (
  <Link key={label} title={label} href={href} aria-label={label}>
    {icon}
  </Link>
);
export default function RootLayout({ children, params }) {console.log(params)
  return (
    <html lang="en">
      <body >
        <header className={styles.nav} id="navbar">
          <Link className={styles.logo} href="/">
            <Logo />
            <h1>Medical <br />Innovative Wellness</h1>
          </Link>
          <nav className={styles.shortMenu}>{iconItems.map(renderIconButton)}</nav>
        </header>
        {children}
        <Suspense >
          <Footer LANG={params.lang || 'en'} />
        </Suspense>
      </body>
    </html>
  );
}
